//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.296
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyncClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsyncClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Accommodation_Cottage_icon {
            get {
                object obj = ResourceManager.GetObject("Accommodation-Cottage-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Buzz_Message_outline_icon {
            get {
                object obj = ResourceManager.GetObject("Buzz-Message-outline-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Buzz_Message_outline_icon1 {
            get {
                object obj = ResourceManager.GetObject("Buzz-Message-outline-icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap house_hi {
            get {
                object obj = ResourceManager.GetObject("house-hi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Industry_Electronics_icon {
            get {
                object obj = ResourceManager.GetObject("Industry-Electronics-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Industry_Electronics_icon1 {
            get {
                object obj = ResourceManager.GetObject("Industry-Electronics-icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kartinki_me_6129 {
            get {
                object obj = ResourceManager.GetObject("kartinki.me-6129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap laptop_wallpapers_hd_i7 {
            get {
                object obj = ResourceManager.GetObject("laptop-wallpapers-hd-i7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LCD_icon {
            get {
                object obj = ResourceManager.GetObject("LCD-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Management_Statistics_icon {
            get {
                object obj = ResourceManager.GetObject("Management-Statistics-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Medicine_Heart_monitor_icon {
            get {
                object obj = ResourceManager.GetObject("Medicine-Heart-monitor-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Medicine_Heart_monitor_icon1 {
            get {
                object obj = ResourceManager.GetObject("Medicine-Heart-monitor-icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Memory_Cards_Torrent_icon {
            get {
                object obj = ResourceManager.GetObject("Memory-Cards-Torrent-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Objects_Scale_icon {
            get {
                object obj = ResourceManager.GetObject("Objects-Scale-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Office_Customer_Male_Light_icon {
            get {
                object obj = ResourceManager.GetObject("Office-Customer-Male-Light-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIT90D_1big {
            get {
                object obj = ResourceManager.GetObject("PIT90D-1big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIT90D_1big1 {
            get {
                object obj = ResourceManager.GetObject("PIT90D-1big1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QutIM_Conference_icon {
            get {
                object obj = ResourceManager.GetObject("QutIM-Conference-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reWalls_com_4040 {
            get {
                object obj = ResourceManager.GetObject("reWalls.com-4040", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reWalls1 {
            get {
                object obj = ResourceManager.GetObject("reWalls1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sections_of_Website_Solutions_icon {
            get {
                object obj = ResourceManager.GetObject("Sections-of-Website-Solutions-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sections_of_Website_Support_icon {
            get {
                object obj = ResourceManager.GetObject("Sections-of-Website-Support-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TO_220_icon {
            get {
                object obj = ResourceManager.GetObject("TO-220-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Users_Remove_user_icon {
            get {
                object obj = ResourceManager.GetObject("Users-Remove-user-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Users_Worker_icon {
            get {
                object obj = ResourceManager.GetObject("Users-Worker-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Very_Basic_Cancel_icon {
            get {
                object obj = ResourceManager.GetObject("Very-Basic-Cancel-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Very_Basic_Key_icon {
            get {
                object obj = ResourceManager.GetObject("Very-Basic-Key-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Very_Basic_Ok_icon {
            get {
                object obj = ResourceManager.GetObject("Very-Basic-Ok-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Very_Basic_Settings_icon {
            get {
                object obj = ResourceManager.GetObject("Very-Basic-Settings-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Very_Basic_Sinchronize_icon {
            get {
                object obj = ResourceManager.GetObject("Very-Basic-Sinchronize-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Weather_Rain_icon {
            get {
                object obj = ResourceManager.GetObject("Weather-Rain-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Weather_Thermometer_icon {
            get {
                object obj = ResourceManager.GetObject("Weather-Thermometer-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Weather_Thermometer_icon1 {
            get {
                object obj = ResourceManager.GetObject("Weather-Thermometer-icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВКЛ {
            get {
                object obj = ResourceManager.GetObject("ВКЛ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВЫКЛ {
            get {
                object obj = ResourceManager.GetObject("ВЫКЛ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Димеры {
            get {
                object obj = ResourceManager.GetObject("Димеры", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Димеры111 {
            get {
                object obj = ResourceManager.GetObject("Димеры111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Фон_1 {
            get {
                object obj = ResourceManager.GetObject("Фон_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Фон_11 {
            get {
                object obj = ResourceManager.GetObject("Фон_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ФОН_2 {
            get {
                object obj = ResourceManager.GetObject("ФОН_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Фон_Итог {
            get {
                object obj = ResourceManager.GetObject("Фон_Итог", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Фон_Итог1 {
            get {
                object obj = ResourceManager.GetObject("Фон_Итог1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
